default:
  server:
    host: '0.0.0.0'
    port: 3000
    cacheDir: './cache'
  pics:
    - 'https://files.vicoli.de/uploads/swappic/nike-just-do-it.jpg'
    - 'https://files.vicoli.de/uploads/swappic/say-works-on-my-machine.jpg'
