default:
  server:
    host: '0.0.0.0'
    port: 3000
    cacheDir: './cache'
  pics:
    - 'https://googledrive.com/host/0B5IRsLTwEO6CRGxVUmE3R3dfWlE'
    - 'https://googledrive.com/host/0B5IRsLTwEO6CM0drVVRLcy1lMlk'
